# Generated by Django 4.2.3 on 2023-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(null=True, to="webapp.tags"),
        ),
    ]
