# Generated by Django 4.2.3 on 2023-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_posts_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="1691219476696.jpg", null=True, upload_to=""
            ),
        ),
    ]
